# Generated by Django 5.0 on 2025-08-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_count', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('user_job', models.CharField(max_length=100)),
                ('review', models.TextField()),
            ],
        ),
    ]
