# Generated by Django 5.0 on 2025-08-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contactformlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformlog',
            name='action_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
